from __future__ import annotations

from contextlib import contextmanager
import os
from pathlib import Path
from types import SimpleNamespace

import pytest
import torch

from osuT5.osuT5.inference.optimized.single import conditional_while_scout
from osuT5.osuT5.inference.optimized.single.conditional_while_scout import (
    ConditionalGraph,
    _CPP_SOURCE,
    _CUDA_SOURCE,
    _raw_graph,
    _require_cuda_scalar,
)


def test_native_source_requires_conditional_while_and_resets_every_launch():
    assert "CUDART_VERSION < 12030" in _CUDA_SOURCE
    assert "cudaGraphCondAssignDefault" in _CUDA_SOURCE
    assert "cudaGraphCondTypeWhile" in _CUDA_SOURCE
    assert "cudaGraphSetConditional" in _CUDA_SOURCE
    assert "cudaGraphAddChildGraphNode" in _CUDA_SOURCE
    assert "cudaGraphInstantiate(conditional)" in _CUDA_SOURCE
    assert "cudaGraphExecDestroy" in _CUDA_SOURCE
    assert "cudaGraphDestroy" in _CUDA_SOURCE


def test_native_source_recursively_rejects_forbidden_body_nodes():
    assert "validate_body_graph(child, label, depth + 1)" in _CUDA_SOURCE
    for allowed in (
        "cudaGraphNodeTypeKernel",
        "cudaGraphNodeTypeMemcpy",
        "cudaGraphNodeTypeMemset",
        "cudaGraphNodeTypeEmpty",
        "cudaGraphNodeTypeGraph",
    ):
        assert allowed in _CUDA_SOURCE
    for forbidden in (
        "cudaGraphNodeTypeHost",
        "cudaGraphNodeTypeEventRecord",
        "cudaGraphNodeTypeWaitEvent",
        "cudaGraphNodeTypeMemAlloc",
    ):
        assert f"case {forbidden}" not in _CUDA_SOURCE


def test_native_module_uses_explicit_pybind_lifecycle_not_autogenerated_calls():
    assert "PYBIND11_MODULE" in _CPP_SOURCE
    assert "build_probe" in _CPP_SOURCE
    assert "build_while" in _CPP_SOURCE
    assert "conditional_destroy" in _CPP_SOURCE


def test_cpu_scalar_fails_before_native_extension_build():
    with pytest.raises(ValueError, match="must be a CUDA tensor"):
        _require_cuda_scalar("counter", torch.zeros(1, dtype=torch.long), dtype=torch.long)


def test_scalar_validation_rejects_dtype_and_shape(monkeypatch):
    fake = SimpleNamespace(
        device=torch.device("cuda", 0),
        numel=lambda: 2,
        dtype=torch.float32,
        is_contiguous=lambda: True,
        shape=(2,),
    )
    monkeypatch.setattr(torch, "Tensor", type(fake))
    with pytest.raises(ValueError, match="one contiguous"):
        _require_cuda_scalar("counter", fake, dtype=torch.long)


def test_raw_graph_requires_keep_graph_handle():
    with pytest.raises(RuntimeError, match="keep_graph=True"):
        _raw_graph("model_graph", object())
    with pytest.raises(RuntimeError, match="null handle"):
        _raw_graph("model_graph", SimpleNamespace(raw_cuda_graph=lambda: 0))


def test_conditional_wrapper_holds_children_and_destroys_once(monkeypatch):
    calls = []

    class Extension:
        @staticmethod
        def build_while(*args):
            calls.append(("build", args))
            return 77

        @staticmethod
        def launch(handle):
            calls.append(("launch", handle))

        @staticmethod
        def destroy(handle):
            calls.append(("destroy", handle))

    model = SimpleNamespace(raw_cuda_graph=lambda: 11)
    tail = SimpleNamespace(raw_cuda_graph=lambda: 22)
    tensors = [object(), object(), object()]

    monkeypatch.setattr(
        conditional_while_scout,
        "_require_cuda_scalar",
        lambda *args, **kwargs: torch.device("cuda", 2),
    )
    monkeypatch.setattr(conditional_while_scout, "_load_extension", Extension)

    guards = []

    @contextmanager
    def device_guard(device):
        guards.append(torch.device(device))
        yield

    monkeypatch.setattr(torch.cuda, "device", device_guard)
    graph = ConditionalGraph.while_children(
        model,
        tail,
        unfinished=tensors[0],
        physical_step=tensors[1],
        stop_step=tensors[2],
    )
    graph.replay()
    graph.close()
    graph.close()

    assert graph.source_graphs == (model, tail)
    assert calls[0][0] == "build"
    assert calls[0][1][:2] == (11, 22)
    assert calls.count(("launch", 77)) == 1
    assert calls.count(("destroy", 77)) == 1
    assert guards == [torch.device("cuda", 2)] * 3
    with pytest.raises(RuntimeError, match="closed"):
        graph.replay()


def test_counter_probe_reports_runtime_and_driver_versions(monkeypatch):
    class Extension:
        @staticmethod
        def build_probe(*args):
            return 12

        @staticmethod
        def runtime_version():
            return 12080

        @staticmethod
        def driver_version():
            return 13020

        @staticmethod
        def destroy(handle):
            pass

    monkeypatch.setattr(
        conditional_while_scout,
        "_require_cuda_scalar",
        lambda *args, **kwargs: torch.device("cuda", 0),
    )
    monkeypatch.setattr(conditional_while_scout, "_load_extension", Extension)

    @contextmanager
    def device_guard(device):
        yield

    monkeypatch.setattr(torch.cuda, "device", device_guard)
    graph = ConditionalGraph.counter_probe(object(), object())
    assert graph.versions() == {"runtime": 12080, "driver": 13020}
    graph.close()


def test_default_engine_import_does_not_import_conditional_scout(tmp_path):
    import subprocess
    import sys

    completed = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "import sys; "
                "import osuT5.osuT5.inference.optimized.single.engine; "
                "print(any(name.endswith('conditional_while_scout') for name in sys.modules))"
            ),
        ],
        check=True,
        capture_output=True,
        text=True,
        env={
            **os.environ,
            "PATH": f"{Path(sys.executable).parent}:{os.environ.get('PATH', '')}",
        },
    )
    assert completed.stdout.strip() == "False"
    assert completed.stderr == ""
